### PR TITLE
1.20.4 Functionality

### LINKED ISSUE #90: [BUG] LiteXpansion does not support 1.20.4
## Description (REQUIRED)

LiteXpansion does not enabled on 1.20.4 due to it using no longer available java classes.

## Steps to reproduce the Issue (REQUIRED)

Download blob.build LiteXpansion. put in minecraft server. see logs 

## Expected behavior (REQUIRED)

It to work on 1.20.4

## Server Log

```

Dec 14 13:45:20 pop-os java[2160069]: [13:45:20 INFO]: [LiteXpansion] Disabling LiteXpansion vDEV - 192 (git 661862ed)
Dec 14 13:45:20 pop-os java[2160069]:         at java.lang.Thread.run(Thread.java:840) ~[?:?]
Dec 14 13:45:20 pop-os java[2160069]:         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:552) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
Dec 14 13:45:20 pop-os java[2160069]:         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-328]
Dec 14 13:45:20 pop-os java[2160069]:         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
Dec 14 13:45:20 pop-os java[2160069]:         at dev.j3fftw.litexpansion.LiteXpansion.onEnable(LiteXpansion.java:43) ~[LiteXpansion.jar:?]
Dec 14 13:45:20 pop-os java[2160069]:         at dev.j3fftw.litexpansion.LiteXpansion.registerEnchantments(LiteXpansion.java:68) ~[LiteXpansion.jar:?]
Dec 14 13:45:20 pop-os java[2160069]: java.lang.NoSuchMethodError: 'boolean org.bukkit.enchantments.Enchantment.isAcceptingRegistrations()'
Dec 14 13:45:20 pop-os java[2160069]: [13:45:20 ERROR]: Error occurred while enabling LiteXpansion vDEV - 192 (git 661862ed) (Is it up to date?)
```
## Environment (REQUIRED)

image

### PR DESCRIPTION
**Pull request by petulikan1**
## Short Description

I've updated the plugin to work with 1.20.4 and ensured that custom glow enchantment remains working on the latest version.

## Additions/Changes/Removals

Due to hard spigot Enchantment class changes, I've had to use NMS (net.minecraft.server) to make the glowing enchant work properly. 
As of that, I had to separate the Core part of the plugin and the NMS part in the projetct so the dependencies wouldn't mix alltogether and possibly even prevent compilation.

## Related Issues

Resolves #90 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with base Slimefun and made sure nothing breaks/unexpected happens.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added which may not be obvious to maintainers.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

**Comment by petulikan1** [comment]
I'd like to also mention that merging this will result breaking the auto-artifact-building system as the Spigot's NMS aren't available online anywhere and can only be built locally.

I've also tried to remove all the NMS parts and change them into reflections, but because we're overriding methods from a class unobtainable during compilation that's sadly not possible without much complex reflection logic and dynamic class creation which would make it more unreadable and hard to read. 


//EDIT

I tried making it with Javassist but without a chance... https://pastebin.com/WwPrMsjG
